"""
Train tiny CatBoost models and emit fixture + reference-prediction JSON.

Outputs (all go to ../test/fixtures/):
    iris.cbm                 - 4 floats, 3 classes (multiclass, integer class labels)
    iris_reference.json      - per-row raw / prob / class predictions
    iris.cbshap              - precomputed TreeSHAP lookup table for iris.cbm
    iris_cbshap_reference.json - per-row SHAP values generated via the Python
                               CBSHAPReader, so the Ruby reader can verify
                               byte-for-byte parity on identical inputs.
    iris_named.cbm           - same model architecture as iris.cbm but trained
                               with explicit string class_names. Exercises
                               Model#metadata and Model#class_names.
    churn_mixed.cbm          - 2 floats + 2 string cats, binary
    churn_mixed_reference.json

Deterministic: every RNG is seeded so re-running produces byte-identical .cbm files.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

import numpy as np
from catboost import CatBoostClassifier, Pool
from sklearn.datasets import load_iris, make_multilabel_classification

from cbshap import CBSHAPReader, write_cbshap
from tree_shap import TreeSHAPExplainer

FIXTURES = Path(__file__).resolve().parent.parent / "test" / "fixtures"
FIXTURES.mkdir(parents=True, exist_ok=True)

SEED = 1337


def train_iris() -> None:
    data = load_iris()
    X = data.data.astype(np.float32)
    y = data.target.astype(np.int32)

    model = CatBoostClassifier(
        iterations=50,
        depth=4,
        learning_rate=0.3,
        loss_function="MultiClass",
        random_seed=SEED,
        verbose=False,
        allow_writing_files=False,
    )
    model.fit(X, y)

    model_path = FIXTURES / "iris.cbm"
    model.save_model(str(model_path))

    # Hand-picked probe rows: 5 per class (15 total) across the dataset.
    probe_idx = list(range(0, 50, 10)) + list(range(50, 100, 10)) + list(range(100, 150, 10))
    probe_X = X[probe_idx]

    raw = model.predict(probe_X, prediction_type="RawFormulaVal")
    prob = model.predict(probe_X, prediction_type="Probability")
    cls = model.predict(probe_X, prediction_type="Class")

    rows = []
    for i, row in enumerate(probe_X):
        rows.append(
            {
                "features": [float(v) for v in row],
                "raw": [float(v) for v in raw[i]],
                "prob": [float(v) for v in prob[i]],
                "class": int(cls[i][0] if cls.ndim == 2 else cls[i]),
            }
        )

    ref = {
        "model": "iris.cbm",
        "float_features_count": 4,
        "cat_features_count": 0,
        "dimensions_count": 3,
        "rows": rows,
    }
    (FIXTURES / "iris_reference.json").write_text(json.dumps(ref, indent=2))
    print(f"wrote {model_path} and iris_reference.json ({len(rows)} rows)")


def write_iris_cbshap() -> None:
    """Build the CBSHAP sidecar for iris.cbm plus a per-row reference JSON.

    The reference SHAP values are generated by the Python CBSHAPReader
    reading the same sidecar — so Ruby is compared to the *decoded*
    values, capturing the float16 quantization exactly. A small
    oracle_rows block holds Algorithm-2 outputs for a looser semantic
    check on the Ruby side.
    """
    model_path = FIXTURES / "iris.cbm"
    sidecar_path = FIXTURES / "iris.cbshap"

    cb = CatBoostClassifier()
    cb.load_model(str(model_path), format="cbm")
    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tmp:
        cb.save_model(tmp.name, format="json")
        tmp_path = Path(tmp.name)
    try:
        json_model = json.loads(tmp_path.read_text())
    finally:
        tmp_path.unlink()

    explainer = TreeSHAPExplainer(json_model)
    shap_table, tree_expected = explainer.precompute_shap_table()

    write_cbshap(
        sidecar_path,
        n_features=explainer.n_features,
        n_classes=explainer.n_classes,
        depth=explainer.depth,
        tree_features=explainer.tree_features,
        tree_borders=explainer.tree_borders,
        shap_table=shap_table,
        tree_expected=tree_expected,
        scale=explainer.scale,
        bias=explainer.bias,
    )

    reader = CBSHAPReader(sidecar_path)

    data = load_iris()
    X = data.data.astype(np.float32)
    probe_idx = list(range(0, 50, 10)) + list(range(50, 100, 10)) + list(range(100, 150, 10))

    rows = []
    for i in probe_idx:
        features = [float(v) for v in X[i]]
        phi = reader.shap_values(np.asarray(features, dtype=np.float64))
        rows.append(
            {
                "features": features,
                "phi": [[float(v) for v in row] for row in phi],
            }
        )

    oracle_rows = []
    for i in probe_idx[:6]:
        features = [float(v) for v in X[i]]
        phi_oracle = explainer.shap_values(np.asarray(features, dtype=np.float64))
        raw = explainer.predict_raw(np.asarray(features, dtype=np.float64))
        oracle_rows.append(
            {
                "features": features,
                "oracle_phi": [[float(v) for v in row] for row in phi_oracle],
                "raw": [float(v) for v in raw],
            }
        )

    ref = {
        "model": "iris.cbm",
        "sidecar": "iris.cbshap",
        "n_features": explainer.n_features,
        "n_classes": explainer.n_classes,
        "feature_names": explainer.feature_names,
        "rows": rows,
        "oracle_rows": oracle_rows,
    }
    (FIXTURES / "iris_cbshap_reference.json").write_text(json.dumps(ref, indent=2))
    size_kb = sidecar_path.stat().st_size / 1024
    print(
        f"wrote {sidecar_path} ({size_kb:.1f} KB) and iris_cbshap_reference.json "
        f"({len(rows)} rows, {len(oracle_rows)} oracle rows)"
    )


def train_iris_named() -> None:
    """Same iris multiclass model as train_iris(), but trained with explicit
    string class_names. The gem's Metadata binding + Model#class_names method
    are exercised against this fixture's class_params key, which stores the
    labels as strings rather than integer indices.

    class_names does NOT affect the trained model's numerical predictions —
    CatBoost internally uses integer indices 0..K-1 regardless. The only
    difference vs. train_iris is what ends up in class_params JSON.
    """
    data = load_iris()
    X = data.data.astype(np.float32)
    y_int = data.target.astype(np.int32)

    class_names = ["setosa", "versicolor", "virginica"]
    # CatBoost requires the training target type to match class_names.
    # Map integer targets to the matching string labels.
    y = np.array(class_names)[y_int]

    model = CatBoostClassifier(
        iterations=50,
        depth=4,
        learning_rate=0.3,
        loss_function="MultiClass",
        random_seed=SEED,
        verbose=False,
        allow_writing_files=False,
        class_names=class_names,
    )
    model.fit(X, y)

    model_path = FIXTURES / "iris_named.cbm"
    model.save_model(str(model_path))
    print(f"wrote {model_path}")


def train_churn_mixed() -> None:
    rng = np.random.default_rng(SEED)
    n = 400

    tiers = np.array(["free", "pro", "premium"])
    regions = np.array(["US", "EU", "APAC"])

    tier = rng.choice(tiers, size=n)
    region = rng.choice(regions, size=n)
    tenure_months = rng.uniform(0, 60, size=n).astype(np.float32)
    monthly_spend = rng.uniform(0, 200, size=n).astype(np.float32)

    # Deterministic-ish binary target from a simple rule + noise.
    score = (
        (tier == "free").astype(float) * 0.4
        + (region == "APAC").astype(float) * 0.2
        + (monthly_spend < 20).astype(float) * 0.3
        - (tenure_months > 24).astype(float) * 0.25
        + rng.normal(0, 0.1, size=n)
    )
    y = (score > 0.35).astype(np.int32)

    X_num = np.stack([tenure_months, monthly_spend], axis=1)
    X = np.column_stack([X_num, tier, region])

    cat_feature_indices = [2, 3]
    feature_names = ["tenure_months", "monthly_spend", "tier", "region"]
    pool = Pool(
        data=X,
        label=y,
        cat_features=cat_feature_indices,
        feature_names=feature_names,
    )

    model = CatBoostClassifier(
        iterations=80,
        depth=4,
        learning_rate=0.2,
        loss_function="Logloss",
        random_seed=SEED,
        verbose=False,
        allow_writing_files=False,
    )
    model.fit(pool)

    model_path = FIXTURES / "churn_mixed.cbm"
    model.save_model(str(model_path))

    # Pick 10 probe rows spanning label classes.
    idx = list(range(0, 10)) + list(range(100, 105)) + list(range(200, 205))
    probe = X[idx]
    probe_pool = Pool(data=probe, cat_features=cat_feature_indices, feature_names=feature_names)

    raw = model.predict(probe_pool, prediction_type="RawFormulaVal")
    # For binary classifiers the C API's "Probability" prediction type returns
    # a single scalar (p of the positive class). Python's high-level predict()
    # expands this to [p0, p1] as a convenience -- we record only the C API's
    # view so the Ruby gem can stay a thin FFI wrapper.
    prob_full = model.predict(probe_pool, prediction_type="Probability")
    cls = model.predict(probe_pool, prediction_type="Class")

    rows = []
    for i in range(len(idx)):
        p_full = np.atleast_1d(prob_full[i])
        p_pos = float(p_full[1]) if p_full.size == 2 else float(p_full[0])
        rows.append(
            {
                "floats": [float(probe[i, 0]), float(probe[i, 1])],
                "cats": [str(probe[i, 2]), str(probe[i, 3])],
                "raw": [float(np.atleast_1d(raw[i])[0])],
                "prob": [p_pos],
                "class": int(np.atleast_1d(cls[i])[0]),
            }
        )

    ref = {
        "model": "churn_mixed.cbm",
        "float_features_count": 2,
        "cat_features_count": 2,
        "dimensions_count": 1,
        "feature_names": feature_names,
        "cat_feature_indices": cat_feature_indices,
        "rows": rows,
    }
    (FIXTURES / "churn_mixed_reference.json").write_text(json.dumps(ref, indent=2))
    print(f"wrote {model_path} and churn_mixed_reference.json ({len(rows)} rows)")


def train_multilabel() -> None:
    """Multi-label classification: each row can have 0..K labels active
    simultaneously. CatBoost handles this via loss_function='MultiLogloss',
    which trains K independent binary classifiers under one model handle.

    Important quirk we exercise here: for MultiLogloss models, Python's
    high-level predict(prediction_type='Probability') returns independent
    per-label sigmoids, but the C API's 'Probability' returns a softmax
    across the K logits -- the C API exposes the independent-sigmoid path
    under the separate 'MultiProbability' prediction type. This fixture
    records both so Ruby can verify it matches the C API literally on
    both paths.
    """
    X, Y = make_multilabel_classification(
        n_samples=400,
        n_features=6,
        n_classes=4,
        n_labels=2,
        allow_unlabeled=True,
        random_state=SEED,
    )
    X = X.astype(np.float32)
    Y = Y.astype(np.int32)

    K = Y.shape[1]

    model = CatBoostClassifier(
        iterations=60,
        depth=4,
        learning_rate=0.2,
        loss_function="MultiLogloss",
        random_seed=SEED,
        verbose=False,
        allow_writing_files=False,
    )
    model.fit(X, Y)

    model_path = FIXTURES / "multilabel.cbm"
    model.save_model(str(model_path))

    # Pick probe rows covering every label-count bucket (0, 1, 2, 3, 4).
    # Take the first few rows from each bucket.
    label_counts = Y.sum(axis=1)
    probe_idx: list[int] = []
    for target_count in range(K + 1):  # 0..K
        bucket = np.where(label_counts == target_count)[0]
        probe_idx.extend(int(i) for i in bucket[:3])
    probe_idx.sort()
    probe_X = X[probe_idx]
    probe_Y = Y[probe_idx]

    raw = model.predict(probe_X, prediction_type="RawFormulaVal")
    # Python's Probability == C API's MultiProbability for MultiLogloss.
    multi_prob = model.predict(probe_X, prediction_type="Probability")
    # The C API's "Probability" for MultiLogloss is softmax-over-logits.
    # We compute it here rather than going through the Python wrapper.
    logits = np.asarray(raw, dtype=np.float64)
    exp_logits = np.exp(logits - logits.max(axis=1, keepdims=True))
    softmax_prob = exp_logits / exp_logits.sum(axis=1, keepdims=True)

    rows = []
    for i in range(len(probe_idx)):
        rows.append(
            {
                "features": [float(v) for v in probe_X[i]],
                "labels": [int(v) for v in probe_Y[i]],
                "label_count": int(probe_Y[i].sum()),
                "raw": [float(v) for v in np.asarray(raw[i]).ravel()],
                "multi_prob": [float(v) for v in np.asarray(multi_prob[i]).ravel()],
                "softmax_prob": [float(v) for v in softmax_prob[i]],
            }
        )

    ref = {
        "model": "multilabel.cbm",
        "float_features_count": 6,
        "cat_features_count": 0,
        "dimensions_count": K,
        "loss_function": "MultiLogloss",
        "rows": rows,
    }
    (FIXTURES / "multilabel_reference.json").write_text(json.dumps(ref, indent=2))
    counts = [r["label_count"] for r in rows]
    print(
        f"wrote {model_path} and multilabel_reference.json "
        f"({len(rows)} rows, label_counts={counts})"
    )


if __name__ == "__main__":
    train_iris()
    write_iris_cbshap()
    train_iris_named()
    train_churn_mixed()
    train_multilabel()
